version: '3.8'

services:
  nats-server1:
    image: nats:latest
    restart: unless-stopped
    container_name: nats_server1
    command: [
      "-p", "4222",
      "-m", "8222",
      "--cluster", "nats://0.0.0.0:6222",
      "--routes", "nats://nats_server2:6222,nats://nats_server3:6222",
      "--cluster_name", "NATS",
      "--name", "nats_server1",
      "--connect_retries", "10"
    ]
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    networks:
      - nats_network

  nats-server2:
    image: nats:latest
    restart: unless-stopped
    container_name: nats_server2
    command: [
      "-p", "4222",
      "-m", "8222",
      "--cluster", "nats://0.0.0.0:6222",
      "--routes", "nats://nats_server1:6222,nats://nats_server3:6222",
      "--cluster_name", "NATS",
      "--name", "nats_server2",
      "--connect_retries", "10"
    ]
    ports:
      - "4223:4222"
      - "8223:8222"
      - "6223:6222"
    networks:
      - nats_network

  nats-server3:
    image: nats:latest
    restart: unless-stopped
    container_name: nats_server3
    command: [
      "-p", "4222",
      "-m", "8222",
      "--cluster", "nats://0.0.0.0:6222",
      "--routes", "nats://nats_server1:6222,nats://nats_server2:6222",
      "--cluster_name", "NATS",
      "--name", "nats_server3",
      "--connect_retries", "10"
    ]
    ports:
      - "4224:4222"
      - "8224:8222"
      - "6224:6222"
    networks:
      - nats_network

networks:
  nats_network:
    driver: bridge
    name: nats_network
