version: '3.8'

services:
  rabbitmq1:
    image: rabbitmq:3.9-management
    hostname: rabbitmq1

    container_name: rabbitmq1
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq1-data:/var/lib/rabbitmq
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    networks:
      rabbitmq:
        aliases:
          - rabbit

  rabbitmq2:
    image: rabbitmq:3.9-management
    hostname: rabbitmq2
    container_name: rabbitmq2
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15673:15672"
      - "5673:5672"
    volumes:
      - rabbitmq2-data:/var/lib/rabbitmq
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    networks:
      rabbitmq:
        aliases:
          - rabbit

  rabbitmq3:
    image: rabbitmq:3.9-management
    hostname: rabbitmq3
    container_name: rabbitmq3
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15674:15672"
      - "5674:5672"
    volumes:
      - rabbitmq3-data:/var/lib/rabbitmq
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    networks:
      rabbitmq:
        aliases:
          - rabbit

networks:
  rabbitmq:
    driver: bridge

volumes:
  rabbitmq1-data:
    driver: local
  rabbitmq2-data:
    driver: local
  rabbitmq3-data:
    driver: local
